### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by myrdstom** [mcdavidlubega/jotr-backend#5]
- [x] Due to the challenges faced with `GithubActions` and databases I recommend `Travis` and `coveralls` for CI. 
- [x] CI should break if tests do not reach 80% test coverage. Bonus points on tests failing if the coverage lowers.

**Comment by mcdavidlubega** [comment]
Implemented CI with Github Actions. I used the [MongoDB In Github Action](https://github.com/marketplace/actions/mongodb-in-github-actions) to run mongodb in githubactions.
I also used the [Create .env file](https://github.com/marketplace/actions/create-env-file) action to create a .env file in github actions. 
The action uses repository secrets to write and populate an env file for use in the github action.

Added test coverage threshholds. (80%) CI breaks if coverage doesnt reach 80%.
